routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::post('contact', 'HomeController@contact')->name('contact');

Auth::routes(['register' => false]);

Route::prefix('admin')->name('adm.')->group(function () {
    Route::get('/', 'AdminController@index')->name('panel');

    Route::get('inicio', 'AdminController@create')->name('home.create');
    Route::post('inicio', 'AdminController@store')->name('home.store');

    Route::get('emp', 'AdminController@empCreate')->name('emp.create');
    Route::post('emp', 'AdminController@empStore')->name('emp.store');

    Route::get('project', 'AdminController@projectCreate')->name('project.create');
    Route::post('project', 'AdminController@projectStore')->name('project.store');

    Route::get('plants', 'AdminController@plantCreate')->name('plants.create');
    Route::post('plants', 'AdminController@plantStore')->name('plants.store');

    Route::get('locations', 'AdminController@locationCreate')->name('locations.create');
    Route::post('locations', 'AdminController@locationStore')->name('locations.store');
    
    Route::get('contacts', 'AdminController@contacts')->name('contact.index');

    Route::prefix('galeria')->name('gallery.')->group(function() {
        Route::get('', 'GalleryController@index')->name('index');
        Route::get('create', 'GalleryController@create')->name('create');
        Route::post('create', 'GalleryController@store')->name('store');
        Route::get('{id}/photos', 'GalleryController@photos')->name('photos');
        Route::post('{id}/photos', 'GalleryController@insertPhotos')->name('insertPhotos');
        Route::get('{id}/photos/delete', 'GalleryController@deletePhotos')->name('deletePhotos');
        Route::get('{id}', 'GalleryController@show')->name('show');
        Route::post('{id}', 'GalleryController@update')->name('update');
        Route::get('{id}/delete', 'GalleryController@delete')->name('delete'); 
    });
});

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Album;
use App\AlbumPhoto;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    protected $album;
    protected $gallery;

    public function __construct(Album $album, AlbumPhoto $ab) {
        $this->middleware('auth');
        $this->album = $album;
        $this->gallery = $ab;
    }

    public function index(Request $request)
    {
        $data = $this->album->all();

        return view('admin.dashboard.gallery.index', compact('data'));
    }

    public function store(Request $request)
    {
        $input = $request->all();

        if (isset($input['cover'])) {
            $imageName = time().'.'.$input['cover']->extension();
            $input['cover']->move(public_path('storage/gallery'), $imageName);

            $input['cover'] = $imageName;
        } else {
            unset($input['cover']);
        }

        $this->album->create($input);

        toastr()->success('Cadastrado');

        return redirect()->route('adm.gallery.index');
    }

    public function show($id)
    {
        
        $data = $this->album->all();
        $album = $this->album->find($id);

        return view('admin.dashboard.gallery.index', compact('data', 'album'));
    }

    public function update($id, Request $request)
    {
        $input = $request->all();

        if (isset($input['cover'])) {
            $imageName = time().'.'.$input['cover']->extension();
            $input['cover']->move(public_path('storage/gallery'), $imageName);

            $input['cover'] = $imageName;
        } else {
            unset($input['cover']);
        }

        $this->album->find($id)->update($input);

        toastr()->success('atualizado');

        return redirect()->route('adm.gallery.index');
    }

    public function photos($id)
    {
        $album = $this->album->find($id);
        $data = $this->gallery->where('album_id', $id)->get();

        return view('admin.dashboard.gallery.photos', compact('data', 'album'));
    }

    public function insertPhotos($id, Request $request)
    {
        $album = $this->album->find($id);
        $input = $request->all();

        foreach($input['photo'] as $key => $photo) {
            $imageName = time().$key.'.'.$photo->extension();
            $photo->move(public_path('storage/gallery'), $imageName);

            $input['photo'] = $imageName;

            $album->photos()->create($input);
        }

        toastr()->success('Fotos cadastradas');

        return redirect()->route('adm.gallery.photos', $id);
    }

    public function deletePhotos($gallery)
    {
        $gallery = $this->gallery->find($gallery);
        $id = $gallery->album_id;

        $gallery->delete();
        
        toastr()->error('Foto apagada');

        return redirect()->route('adm.gallery.photos', $id);
    }
}

resources/views/admin/dashboard/gallery/desc.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Descrição</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Título
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateDesc']) !!}
              PT: {!! Form::textarea('pt', $pt->desc, ['class' => 'form-control', 'required']) !!}
              EN: {!! Form::textarea('en', $en->desc, ['class' => 'form-control', 'required']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/gallery/form.blade.php
<section class="section">
  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> Cadastrar
            </h4>
          </div>
          <div class="card-body row">
            @if(isset($album))
                {!! Form::model($album, ['route' => ['adm.gallery.update', $album->id], 'files' => true]) !!}
            @else
                {!! Form::open(['route' => 'adm.gallery.store', 'files' => true]) !!}
            @endif
              Título: {!! Form::text('title', null, ['class' => 'form-control', 'required']) !!}
              <br>
              Capa: {!! Form::file('cover') !!}
              <br>
              <br>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

resources/views/admin/dashboard/gallery/index.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header d-flex justify-content-between">
    <h1>Albums</h1>
  </div>
  @include('admin.dashboard.gallery.form')
  <div class="section-body">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-12">
        <div class="card dashboard-funil-full">
          <table class="table table-responsive">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Opções</th>
              </tr>
            </thead>
            <tbody>
              @foreach($data as $album)
              <tr>
                <th scope="row">{{$album->id}}</th>
                <td>{{$album->title}}</td>
                <td>
                  <a href="{{ route('adm.gallery.show', $album->id) }}">Editar</a> | 
                  <a href="{{ route('adm.gallery.photos', $album->id) }}">Fotos</a> | 
                  <a href="{{ route('adm.gallery.delete', $album->id)}} " onclick="return confirm('Deseja mesmo apagar?')">Apagar</a>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/gallery/number.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Nossos Números</h1>
  </div>

  <div class="section-body">
    <div class="row">
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> PT
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateNumber']) !!}
              {!! Form::hidden('lang', 'pt') !!}
              {!! Form::label('t', 'Seção 1') !!}
              {!! Form::text('t1', $pt->t1, ['class' => 'form-control']) !!}
              {!! Form::number('n1', $pt->n1, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 2') !!}
              {!! Form::text('t2', $pt->t2, ['class' => 'form-control']) !!}
              {!! Form::number('n2', $pt->n2, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 3') !!}
              {!! Form::text('t3', $pt->t3, ['class' => 'form-control']) !!}
              {!! Form::number('n3', $pt->n3, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 4') !!}
              {!! Form::text('t4', $pt->t4, ['class' => 'form-control']) !!}
              {!! Form::number('n4', $pt->n4, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 5') !!}
              {!! Form::text('t5', $pt->t5, ['class' => 'form-control']) !!}
              {!! Form::number('n5', $pt->n5, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 6') !!}
              {!! Form::text('t6', $pt->t6, ['class' => 'form-control']) !!}
              {!! Form::number('n6', $pt->n6, ['class' => 'form-control']) !!}
              <br>
              <a href="{{url()->previous()}}" class="btn btn-primary">Voltar</a>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
      <div class="col-6 col-md-6 col-lg-6">
        <div class="card dashboard-funil-full">
          <div class="card-header">
            <h4>
              <i class="far fa-star lga"></i> EN
            </h4>
          </div>
          <div class="card-body row">
              {!! Form::open(['route' => 'adm.service.updateNumber']) !!}
              {!! Form::hidden('lang', 'en') !!}
              {!! Form::label('t', 'Seção 1') !!}
              {!! Form::text('t1', $en->t1, ['class' => 'form-control']) !!}
              {!! Form::text('n1', $en->n1, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 2') !!}
              {!! Form::text('t2', $en->t2, ['class' => 'form-control']) !!}
              {!! Form::text('n2', $en->n2, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 3') !!}
              {!! Form::text('t3', $en->t3, ['class' => 'form-control']) !!}
              {!! Form::text('n3', $en->n3, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 4') !!}
              {!! Form::text('t4', $en->t4, ['class' => 'form-control']) !!}
              {!! Form::text('n4', $en->n4, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 5') !!}
              {!! Form::text('t5', $en->t5, ['class' => 'form-control']) !!}
              {!! Form::text('n5', $en->n5, ['class' => 'form-control']) !!}
              <br>
              {!! Form::label('t', 'Seção 6') !!}
              {!! Form::text('t6', $en->t6, ['class' => 'form-control']) !!}
              {!! Form::text('n6', $en->n6, ['class' => 'form-control']) !!}
              <br>
              {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>


@endsection

resources/views/admin/dashboard/gallery/photos.blade.php
@extends('admin.layouts.default')

@section('content')

<section class="section">
  <div class="section-header d-flex justify-content-between">
    <h1>Fotos - {{$album->title}}</h1>
  </div>
  <div class="section-body">
    <div class="card dashboard-funil-full">
    <div class="row m-4">
      <div class="col-md-3">
        {!! Form::open(['route' => ['adm.gallery.insertPhotos', $album->id], 'files' => true])!!}
          {!! Form::label('asd', 'Selecionar Fotos')!!}
          <br>
          {!! Form::file('photo[]', ['multiple' => true]) !!}
          <br><br>
          {!! Form::submit('Enviar', ['class' => 'btn btn-success']) !!}
        {!! Form::close() !!}
      </div>
      @foreach($data as $photo)
        <div class="col-md-3 ">

          <img src="{{url('/storage/gallery/'.$photo->photo)}}" class="cover-img rounded m-3" width="200px" height="200px">
          <a class="btn btn-danger btn-xs" href="{{ route('adm.gallery.deletePhotos', $photo->id) }}" onclick="return confirm('Deseja mesmo excluir?')">X</a>
        </div>
      @endforeach
      </div>
    </div>
  </div>

</section>


@endsection